In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("bankloandataset.csv")
print(df)

    Age  Income  Credit_Score  Loan_Amount     Employment Loan_Approved
0  25.0   30000           650       200000       Salaried           Yes
1  42.0   75000           780       500000       Business           Yes
2  31.0   25000           590       300000  Self-employed            No
3   NaN   45000           720       250000            NaN           Yes
4  50.0   90000           810       700000       Business           Yes
5  36.0   40000           610       350000       Salaried            No
6  29.0   55000           740       300000  Self-employed           Yes
7  46.0   35000           580       450000       Salaried            No
8  33.0   68000           760       400000       Business           Yes
9  27.0   22000           560       180000       Salaried            No

In [3]:
df.shape

(10, 6)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Age            9 non-null      float64
 1   Income         10 non-null     int64
 2   Credit_Score   10 non-null     int64
 3   Loan_Amount    10 non-null     int64
 4   Employment     9 non-null      object
 5   Loan_Approved  10 non-null     object
dtypes: float64(1), int64(3), object(2)
memory usage: 612.0+ bytes

In [5]:
df.head()

    Age  Income  Credit_Score  Loan_Amount     Employment Loan_Approved
0  25.0   30000           650       200000       Salaried           Yes
1  42.0   75000           780       500000       Business           Yes
2  31.0   25000           590       300000  Self-employed            No
3   NaN   45000           720       250000            NaN           Yes
4  50.0   90000           810       700000       Business           Yes

In [6]:
df.tail()

    Age  Income  Credit_Score  Loan_Amount     Employment Loan_Approved
5  36.0   40000           610       350000       Salaried            No
6  29.0   55000           740       300000  Self-employed           Yes
7  46.0   35000           580       450000       Salaried            No
8  33.0   68000           760       400000       Business           Yes
9  27.0   22000           560       180000       Salaried            No

In [7]:
df.isnull().sum()

Age              1
Income           0
Credit_Score     0
Loan_Amount      0
Employment       1
Loan_Approved    0
dtype: int64

In [8]:
df["Age"].mean()

np.float64(35.44444444444444)

In [9]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

         Age  Income  Credit_Score  Loan_Amount     Employment Loan_Approved
0  25.000000   30000           650       200000       Salaried           Yes
1  42.000000   75000           780       500000       Business           Yes
2  31.000000   25000           590       300000  Self-employed            No
3  35.444444   45000           720       250000            NaN           Yes
4  50.000000   90000           810       700000       Business           Yes
5  36.000000   40000           610       350000       Salaried            No
6  29.000000   55000           740       300000  Self-employed           Yes
7  46.000000   35000           580       450000       Salaried            No
8  33.000000   68000           760       400000       Business           Yes
9  27.000000   22000           560       180000       Salaried            No

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
le=LabelEncoder()

In [12]:
df['Employment']=le.fit_transform(df['Employment'])

In [13]:
df["Employment"]=le.fit_transform(df["Employment"])
df["Loan_Approved"]=le.fit_transform(df["Loan_Approved"])
df["Loan_Approved"]=le.fit_transform(df["Loan_Approved"])
df

         Age  Income  Credit_Score  Loan_Amount  Employment  Loan_Approved
0  25.000000   30000           650       200000           1              1
1  42.000000   75000           780       500000           0              1
2  31.000000   25000           590       300000           2              0
3  35.444444   45000           720       250000           3              1
4  50.000000   90000           810       700000           0              1
5  36.000000   40000           610       350000           1              0
6  29.000000   55000           740       300000           2              1
7  46.000000   35000           580       450000           1              0
8  33.000000   68000           760       400000           0              1
9  27.000000   22000           560       180000           1              0

In [14]:
X=df.drop("Loan_Approved",axis=1)
X

         Age  Income  Credit_Score  Loan_Amount  Employment
0  25.000000   30000           650       200000           1
1  42.000000   75000           780       500000           0
2  31.000000   25000           590       300000           2
3  35.444444   45000           720       250000           3
4  50.000000   90000           810       700000           0
5  36.000000   40000           610       350000           1
6  29.000000   55000           740       300000           2
7  46.000000   35000           580       450000           1
8  33.000000   68000           760       400000           0
9  27.000000   22000           560       180000           1

In [15]:
y=df["Loan_Approved"]
y

0    1
1    1
2    0
3    1
4    1
5    0
6    1
7    0
8    1
9    0
Name: Loan_Approved, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split,KFold

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [18]:
X_train.shape

(8, 5)

In [19]:
X_test.shape

(2, 5)

In [20]:
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
X_train["Credit_Score"]= scaler.fit_transform(X_train[['Credit_Score']])
X_train

         Age  Income  Credit_Score  Loan_Amount  Employment
5  36.000000   40000     -0.565968       350000           1
0  25.000000   30000     -0.089363       200000           1
7  46.000000   35000     -0.923421       450000           1
2  31.000000   25000     -0.804270       300000           2
9  27.000000   22000     -1.161723       180000           1
4  50.000000   90000      1.817054       700000           0
3  35.444444   45000      0.744694       250000           3
6  29.000000   55000      0.982997       300000           2

In [26]:
X_train['Credit_Score'].sum()

np.float64(0.0)